// apps/cart/src/app/app.component.ts
import { Component, NgZone, OnDestroy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { config, Product, PubSub } from '@micro-frontends/shared';

@Component({
  standalone: true,
  imports: [CommonModule],
  selector: 'app-cart-component',
  template: `
    <div class="simple-card">
      <div class="header">
        <img [src]="logoUrl" alt="Logo" class="logo" />
        <h1>
          Cart App 👋
        </h1>
      </div>
      <div class="content">
        <table *ngIf="cartProducts.length > 0; else emptyCart">
          <thead>
            <tr>
              <th>Product Name</th>
              <th>Price</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let product of cartProducts; let i = index">
              <td>{{ product.name }}</td>
              <td>\${{ product.price }}</td>
              <td class="select-column">
                <button (click)="removeFromCart(i)">-</button>
              </td>
            </tr>
          </tbody>
        </table>
        <ng-template #emptyCart>
          <p>Your cart is currently empty. Add some products to see them here.</p>
        </ng-template>
      </div>
    </div>
  `,
  styles: [
    `
      .select-column {
        width: 2rem;
      }
      .select-column button:hover {
        cursor: pointer;
      }
    `,
  ],
})
export class AppComponent implements OnInit, OnDestroy {
  logoUrl = `${config.cartUrl}/logo.png`;
  cartProducts: Product[] = [];
  unsubscribeProductAdd: VoidFunction;
  unsubscribeProductRemove: VoidFunction;

  constructor(private zone: NgZone) {
    this.cartProducts = [];
    this.unsubscribeProductAdd = () => { };
    this.unsubscribeProductRemove = () => { };
  }



  removeFromCart(index: number): void {
   PubSub.publish('product-removed', this.cartProducts[index]);
  }

  ngOnInit(): void {
    this.unsubscribeProductAdd = PubSub.subscribe('product-added', (product: Product) => {
      this.zone.run(() => {
        this.cartProducts.push(product);
      });
    });

    this.unsubscribeProductRemove = PubSub.subscribe('product-removed', (product: Product) => {
      this.zone.run(() => {
        this.cartProducts = this.cartProducts.filter((p) => p.id !== product.id);
      });
    });
  }

  ngOnDestroy(): void {
    this.unsubscribeProductAdd();
    this.unsubscribeProductRemove();
  }
}

// apps/products/src/App.svelte
<script>
  import '@micro-frontends/shared-styles';
  import { config, PubSub } from '@micro-frontends/shared';
  import { onMount } from 'svelte';

  let products = [
    { id: 1, name: 'Product 1', price: 10 },
    { id: 2, name: 'Product 2', price: 20 },
    { id: 3, name: 'Product 3', price: 30 },
  ];

  let selectedProducts = new Set();
  const logoUrl = `${config.productsUrl}/assets/logo.png`;

  onMount(() => {
    const unsubscribeRemove = PubSub.subscribe('product-removed', (product) => {
      selectedProducts.delete(product.id);
      selectedProducts = new Set(selectedProducts);
    });

    const unsubscribeAdded = PubSub.subscribe('product-added', (product) => {
      selectedProducts.add(product.id);
      selectedProducts = new Set(selectedProducts);
    });

    return () => {
      unsubscribeRemove();
      unsubscribeAdded();
    };
  });

  function toggleSelection(product) {
    if (selectedProducts.has(product.id)) {
      PubSub.publish('product-removed', product);
    } else {
      PubSub.publish('product-added', product);
    }
  }
</script>

<div class="simple-card">
  <div class="header">
    <img src={logoUrl} alt="Logo" class="logo" />
    <h1>Products App 👋</h1>
  </div>
  <div class="content">
    <table>
      <thead>
        <tr>
          <th></th>
          <th>Name</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        {#each products as product}
          <tr>
            <td class="select-column">
              <input
                type="checkbox"
                checked={selectedProducts.has(product.id)}
                on:change={() => toggleSelection(product)}
              />
            </td>
            <td>{product.name}</td>
            <td>${product.price}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>

<style>
  .select-column {
    width: 2rem;
  }
</style>
